import { PrismaClient, ItemRarity } from '@prisma/client';

const prisma = new PrismaClient();

export const pets = [
  // Common Pets (Easy to get)
  {
    name: 'Sparkle Puppy',
    description: 'A playful puppy that sparkles with excitement when you solve problems!',
    rarity: 'COMMON' as ItemRarity,
    coinsCost: 500,
    gemsCost: 0,
    requiredLevel: 1,
    imageUrl: '/assets/pets/sparkle-puppy.png',
    baseAbility: 'coin_boost',
    abilityValue: 5, // 5% coin boost at level 1
    personality: 'Energetic and loyal, loves to celebrate your victories',
  },
  {
    name: 'Math Mouse',
    description: 'A clever mouse that squeaks with joy at every correct answer',
    rarity: 'COMMON' as ItemRarity,
    coinsCost: 500,
    gemsCost: 0,
    requiredLevel: 1,
    imageUrl: '/assets/pets/math-mouse.png',
    baseAbility: 'xp_boost',
    abilityValue: 5,
    personality: 'Curious and quick, always eager to learn',
  },
  {
    name: 'Bubble Bunny',
    description: 'A fluffy bunny that bounces in bubbles when you combo!',
    rarity: 'COMMON' as ItemRarity,
    coinsCost: 750,
    gemsCost: 0,
    requiredLevel: 3,
    imageUrl: '/assets/pets/bubble-bunny.png',
    baseAbility: 'hint_discount',
    abilityValue: 5,
    personality: 'Gentle and supportive, helps when you need it',
  },
  {
    name: 'Number Newt',
    description: 'A tiny newt that changes colors with your streak',
    rarity: 'COMMON' as ItemRarity,
    coinsCost: 600,
    gemsCost: 0,
    requiredLevel: 2,
    imageUrl: '/assets/pets/number-newt.png',
    baseAbility: 'coin_boost',
    abilityValue: 5,
    personality: 'Shy but colorful, grows braver as you level up',
  },

  // Uncommon Pets
  {
    name: 'Algebra Owl',
    description: 'A wise owl that hoots encouragement during tough problems',
    rarity: 'UNCOMMON' as ItemRarity,
    coinsCost: 1500,
    gemsCost: 10,
    requiredLevel: 5,
    imageUrl: '/assets/pets/algebra-owl.png',
    baseAbility: 'xp_boost',
    abilityValue: 10,
    personality: 'Wise and patient, helps you think through challenges',
  },
  {
    name: 'Fractal Fox',
    description: 'A magical fox whose tail creates geometric patterns',
    rarity: 'UNCOMMON' as ItemRarity,
    coinsCost: 1800,
    gemsCost: 15,
    requiredLevel: 7,
    imageUrl: '/assets/pets/fractal-fox.png',
    baseAbility: 'coin_boost',
    abilityValue: 10,
    personality: 'Mysterious and clever, loves pattern puzzles',
  },
  {
    name: 'Decimal Dragon',
    description: 'A tiny dragon that breathes decimal dust',
    rarity: 'UNCOMMON' as ItemRarity,
    coinsCost: 2000,
    gemsCost: 20,
    requiredLevel: 8,
    imageUrl: '/assets/pets/decimal-dragon.png',
    baseAbility: 'hint_discount',
    abilityValue: 10,
    personality: 'Fierce but friendly, roars with pride at your success',
  },
  {
    name: 'Geometry Cat',
    description: 'A sleek cat that draws perfect circles when it purrs',
    rarity: 'UNCOMMON' as ItemRarity,
    coinsCost: 1600,
    gemsCost: 12,
    requiredLevel: 6,
    imageUrl: '/assets/pets/geometry-cat.png',
    baseAbility: 'xp_boost',
    abilityValue: 10,
    personality: 'Independent and precise, loves symmetry',
  },

  // Rare Pets
  {
    name: 'Phoenix Pi',
    description: 'A legendary phoenix that leaves a trail of π symbols',
    rarity: 'RARE' as ItemRarity,
    coinsCost: 0,
    gemsCost: 50,
    requiredLevel: 10,
    imageUrl: '/assets/pets/phoenix-pi.png',
    baseAbility: 'coin_boost',
    abilityValue: 15,
    personality: 'Majestic and inspiring, rises with you through challenges',
  },
  {
    name: 'Quantum Koala',
    description: 'A koala that exists in multiple states until you solve a problem',
    rarity: 'RARE' as ItemRarity,
    coinsCost: 0,
    gemsCost: 60,
    requiredLevel: 12,
    imageUrl: '/assets/pets/quantum-koala.png',
    baseAbility: 'xp_boost',
    abilityValue: 15,
    personality: 'Calm and mysterious, helps you see multiple solutions',
  },
  {
    name: 'Infinity Wolf',
    description: 'A cosmic wolf with an ∞ symbol on its forehead',
    rarity: 'RARE' as ItemRarity,
    coinsCost: 0,
    gemsCost: 75,
    requiredLevel: 15,
    imageUrl: '/assets/pets/infinity-wolf.png',
    baseAbility: 'hint_discount',
    abilityValue: 15,
    personality: 'Loyal and boundless, never gives up on you',
  },

  // Epic Pets
  {
    name: 'Fractal Phoenix',
    description: 'A magnificent phoenix made of infinite fractals',
    rarity: 'EPIC' as ItemRarity,
    coinsCost: 0,
    gemsCost: 150,
    requiredLevel: 20,
    imageUrl: '/assets/pets/fractal-phoenix.png',
    baseAbility: 'coin_boost',
    abilityValue: 20,
    personality: 'Breathtaking and powerful, embodies infinite potential',
  },
  {
    name: 'Cosmic Tiger',
    description: 'A tiger made of stars and nebulas',
    rarity: 'EPIC' as ItemRarity,
    coinsCost: 0,
    gemsCost: 175,
    requiredLevel: 22,
    imageUrl: '/assets/pets/cosmic-tiger.png',
    baseAbility: 'xp_boost',
    abilityValue: 20,
    personality: 'Powerful and cosmic, roars with the sound of galaxies',
  },
  {
    name: 'Theorem Thunderbird',
    description: 'A massive bird that creates proof lightning',
    rarity: 'EPIC' as ItemRarity,
    coinsCost: 0,
    gemsCost: 200,
    requiredLevel: 25,
    imageUrl: '/assets/pets/theorem-thunderbird.png',
    baseAbility: 'hint_discount',
    abilityValue: 20,
    personality: 'Electrifying and brilliant, strikes with insight',
  },

  // Legendary Pets
  {
    name: 'Euler\'s Eagle',
    description: 'The legendary eagle of the great mathematician Euler',
    rarity: 'LEGENDARY' as ItemRarity,
    coinsCost: 0,
    gemsCost: 500,
    requiredLevel: 30,
    imageUrl: '/assets/pets/eulers-eagle.png',
    baseAbility: 'coin_boost',
    abilityValue: 25,
    personality: 'Legendary and wise, carries the knowledge of centuries',
    isLimitedEdition: true,
  },
  {
    name: 'Gauss\'s Griffin',
    description: 'A mythical griffin blessed by the Prince of Mathematics',
    rarity: 'LEGENDARY' as ItemRarity,
    coinsCost: 0,
    gemsCost: 600,
    requiredLevel: 35,
    imageUrl: '/assets/pets/gauss-griffin.png',
    baseAbility: 'xp_boost',
    abilityValue: 25,
    personality: 'Noble and brilliant, sees patterns others cannot',
    isLimitedEdition: true,
  },

  // Mythic Pets (Ultra Rare)
  {
    name: 'Infinity Serpent',
    description: 'The cosmic serpent that forms an eternal mobius strip',
    rarity: 'MYTHIC' as ItemRarity,
    coinsCost: 0,
    gemsCost: 1000,
    requiredLevel: 40,
    imageUrl: '/assets/pets/infinity-serpent.png',
    baseAbility: 'all_boost',
    abilityValue: 30,
    personality: 'Eternal and omniscient, sees all mathematical truths',
    isLimitedEdition: true,
  },
  {
    name: 'Archimedes Avatar',
    description: 'The divine manifestation of pure mathematical genius',
    rarity: 'MYTHIC' as ItemRarity,
    coinsCost: 0,
    gemsCost: 1500,
    requiredLevel: 50,
    imageUrl: '/assets/pets/archimedes-avatar.png',
    baseAbility: 'all_boost',
    abilityValue: 50,
    personality: 'Transcendent and all-knowing, the ultimate math companion',
    isLimitedEdition: true,
  },

  // Event-Exclusive Pets
  {
    name: 'Holiday Helper',
    description: 'A festive companion that appears during special events',
    rarity: 'RARE' as ItemRarity,
    coinsCost: 0,
    gemsCost: 100,
    requiredLevel: 10,
    imageUrl: '/assets/pets/holiday-helper.png',
    baseAbility: 'coin_boost',
    abilityValue: 15,
    personality: 'Cheerful and festive, spreads holiday joy',
    isLimitedEdition: true,
  },
  {
    name: 'Summer Surfer',
    description: 'A cool pet that rides waves of numbers',
    rarity: 'RARE' as ItemRarity,
    coinsCost: 0,
    gemsCost: 100,
    requiredLevel: 10,
    imageUrl: '/assets/pets/summer-surfer.png',
    baseAbility: 'xp_boost',
    abilityValue: 15,
    personality: 'Laid-back and cool, makes learning feel like vacation',
    isLimitedEdition: true,
  },
];

export async function seedPets() {
  console.log('🐾 Seeding pets...');

  for (const pet of pets) {
    await prisma.pet.upsert({
      where: { name: pet.name },
      create: pet,
      update: pet,
    });
  }

  console.log(`✅ Seeded ${pets.length} pets`);
}

export default seedPets;