import { PrismaClient, QuestType, QuestDifficulty } from '@prisma/client';

const prisma = new PrismaClient();

export const questTemplates = [
  // SOLVE_PROBLEMS Quests
  {
    name: 'Math Warm-Up',
    description: 'Solve 5 problems to get your brain warmed up!',
    type: 'SOLVE_PROBLEMS' as QuestType,
    difficulty: 'EASY' as QuestDifficulty,
    targetValue: 5,
    coinReward: 50,
    xpReward: 25,
    gemReward: 0,
  },
  {
    name: 'Problem Solver',
    description: 'Solve 15 problems today',
    type: 'SOLVE_PROBLEMS' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 15,
    coinReward: 100,
    xpReward: 75,
    gemReward: 5,
  },
  {
    name: 'Math Marathon',
    description: 'Solve 30 problems in one day!',
    type: 'SOLVE_PROBLEMS' as QuestType,
    difficulty: 'HARD' as QuestDifficulty,
    targetValue: 30,
    coinReward: 250,
    xpReward: 150,
    gemReward: 15,
  },
  {
    name: 'Speed Demon',
    description: 'Solve 10 problems quickly',
    type: 'SOLVE_PROBLEMS' as QuestType,
    difficulty: 'EASY' as QuestDifficulty,
    targetValue: 10,
    coinReward: 75,
    xpReward: 50,
    gemReward: 0,
  },

  // PERFECT_ACCURACY Quests
  {
    name: 'Accuracy Ace',
    description: 'Get 3 problems correct in a row',
    type: 'PERFECT_ACCURACY' as QuestType,
    difficulty: 'EASY' as QuestDifficulty,
    targetValue: 3,
    coinReward: 60,
    xpReward: 40,
    gemReward: 0,
  },
  {
    name: 'Perfect Five',
    description: 'Get 5 problems correct in a row',
    type: 'PERFECT_ACCURACY' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 5,
    coinReward: 120,
    xpReward: 80,
    gemReward: 5,
  },
  {
    name: 'Flawless Victory',
    description: 'Get 10 problems correct in a row!',
    type: 'PERFECT_ACCURACY' as QuestType,
    difficulty: 'HARD' as QuestDifficulty,
    targetValue: 10,
    coinReward: 300,
    xpReward: 200,
    gemReward: 20,
  },
  {
    name: 'No Mistakes',
    description: 'Get 7 problems correct in a row',
    type: 'PERFECT_ACCURACY' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 7,
    coinReward: 180,
    xpReward: 120,
    gemReward: 10,
  },

  // TIME_CHALLENGE Quests
  {
    name: 'Quick Thinker',
    description: 'Solve 3 problems under the time limit',
    type: 'TIME_CHALLENGE' as QuestType,
    difficulty: 'EASY' as QuestDifficulty,
    targetValue: 3,
    coinReward: 50,
    xpReward: 30,
    gemReward: 0,
  },
  {
    name: 'Speed Master',
    description: 'Solve 5 problems under the time limit',
    type: 'TIME_CHALLENGE' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 5,
    coinReward: 100,
    xpReward: 70,
    gemReward: 5,
  },
  {
    name: 'Lightning Fast',
    description: 'Solve 10 problems under the time limit!',
    type: 'TIME_CHALLENGE' as QuestType,
    difficulty: 'HARD' as QuestDifficulty,
    targetValue: 10,
    coinReward: 250,
    xpReward: 150,
    gemReward: 15,
  },

  // TOPIC_MASTERY Quests
  {
    name: 'Fraction Focus',
    description: 'Solve 5 fraction problems',
    type: 'TOPIC_MASTERY' as QuestType,
    difficulty: 'EASY' as QuestDifficulty,
    targetValue: 5,
    coinReward: 60,
    xpReward: 40,
    gemReward: 0,
    metadata: { topic: 'fractions' },
  },
  {
    name: 'Decimal Dynamo',
    description: 'Solve 5 decimal problems',
    type: 'TOPIC_MASTERY' as QuestType,
    difficulty: 'EASY' as QuestDifficulty,
    targetValue: 5,
    coinReward: 60,
    xpReward: 40,
    gemReward: 0,
    metadata: { topic: 'decimals' },
  },
  {
    name: 'Algebra All-Star',
    description: 'Solve 8 algebra problems',
    type: 'TOPIC_MASTERY' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 8,
    coinReward: 120,
    xpReward: 80,
    gemReward: 5,
    metadata: { topic: 'algebra' },
  },
  {
    name: 'Geometry Genius',
    description: 'Solve 8 geometry problems',
    type: 'TOPIC_MASTERY' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 8,
    coinReward: 120,
    xpReward: 80,
    gemReward: 5,
    metadata: { topic: 'geometry' },
  },
  {
    name: 'Percentage Pro',
    description: 'Solve 5 percentage problems',
    type: 'TOPIC_MASTERY' as QuestType,
    difficulty: 'EASY' as QuestDifficulty,
    targetValue: 5,
    coinReward: 60,
    xpReward: 40,
    gemReward: 0,
    metadata: { topic: 'percentages' },
  },

  // STREAK_BUILDER Quests
  {
    name: 'Keep It Going',
    description: 'Maintain a 3-day streak',
    type: 'STREAK_BUILDER' as QuestType,
    difficulty: 'EASY' as QuestDifficulty,
    targetValue: 3,
    coinReward: 75,
    xpReward: 50,
    gemReward: 5,
  },
  {
    name: 'Dedicated Learner',
    description: 'Maintain a 5-day streak',
    type: 'STREAK_BUILDER' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 5,
    coinReward: 150,
    xpReward: 100,
    gemReward: 10,
  },
  {
    name: 'Unstoppable',
    description: 'Maintain a 7-day streak!',
    type: 'STREAK_BUILDER' as QuestType,
    difficulty: 'HARD' as QuestDifficulty,
    targetValue: 7,
    coinReward: 300,
    xpReward: 200,
    gemReward: 25,
  },

  // HARD_PROBLEMS Quests
  {
    name: 'Challenge Accepted',
    description: 'Solve 3 hard problems (difficulty 8+)',
    type: 'HARD_PROBLEMS' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 3,
    coinReward: 150,
    xpReward: 100,
    gemReward: 10,
  },
  {
    name: 'Brain Buster',
    description: 'Solve 5 hard problems (difficulty 8+)',
    type: 'HARD_PROBLEMS' as QuestType,
    difficulty: 'HARD' as QuestDifficulty,
    targetValue: 5,
    coinReward: 300,
    xpReward: 200,
    gemReward: 20,
  },
  {
    name: 'Expert Challenge',
    description: 'Solve 10 hard problems (difficulty 8+)',
    type: 'HARD_PROBLEMS' as QuestType,
    difficulty: 'HARD' as QuestDifficulty,
    targetValue: 10,
    coinReward: 500,
    xpReward: 350,
    gemReward: 40,
  },

  // SOCIAL_PLAY Quests
  {
    name: 'Friendly Competition',
    description: 'Play 1 game with a friend',
    type: 'SOCIAL_PLAY' as QuestType,
    difficulty: 'EASY' as QuestDifficulty,
    targetValue: 1,
    coinReward: 50,
    xpReward: 30,
    gemReward: 0,
  },
  {
    name: 'Social Butterfly',
    description: 'Play 3 games with friends',
    type: 'SOCIAL_PLAY' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 3,
    coinReward: 120,
    xpReward: 80,
    gemReward: 5,
  },
  {
    name: 'Squad Goals',
    description: 'Play 5 games with friends',
    type: 'SOCIAL_PLAY' as QuestType,
    difficulty: 'HARD' as QuestDifficulty,
    targetValue: 5,
    coinReward: 250,
    xpReward: 150,
    gemReward: 15,
  },

  // BOSS_BATTLE Quests
  {
    name: 'Boss Hunter',
    description: 'Attempt a boss battle',
    type: 'BOSS_BATTLE' as QuestType,
    difficulty: 'EASY' as QuestDifficulty,
    targetValue: 1,
    coinReward: 100,
    xpReward: 75,
    gemReward: 5,
  },
  {
    name: 'Boss Slayer',
    description: 'Defeat 1 boss',
    type: 'BOSS_BATTLE' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 1,
    coinReward: 200,
    xpReward: 150,
    gemReward: 15,
  },
  {
    name: 'Boss Dominator',
    description: 'Defeat 3 bosses',
    type: 'BOSS_BATTLE' as QuestType,
    difficulty: 'HARD' as QuestDifficulty,
    targetValue: 3,
    coinReward: 500,
    xpReward: 350,
    gemReward: 40,
  },

  // COLLECTION Quests
  {
    name: 'Treasure Hunter',
    description: 'Open 1 treasure chest',
    type: 'COLLECTION' as QuestType,
    difficulty: 'EASY' as QuestDifficulty,
    targetValue: 1,
    coinReward: 50,
    xpReward: 30,
    gemReward: 0,
  },
  {
    name: 'Loot Collector',
    description: 'Open 3 treasure chests',
    type: 'COLLECTION' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 3,
    coinReward: 120,
    xpReward: 80,
    gemReward: 5,
  },
  {
    name: 'Avatar Fashionista',
    description: 'Purchase 3 avatar items',
    type: 'COLLECTION' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 3,
    coinReward: 150,
    xpReward: 100,
    gemReward: 10,
  },
  {
    name: 'Pet Collector',
    description: 'Purchase 1 new pet',
    type: 'COLLECTION' as QuestType,
    difficulty: 'MEDIUM' as QuestDifficulty,
    targetValue: 1,
    coinReward: 100,
    xpReward: 75,
    gemReward: 10,
  },

  // Special Weekly Quests
  {
    name: 'Weekly Warrior',
    description: 'Solve 100 problems this week',
    type: 'SOLVE_PROBLEMS' as QuestType,
    difficulty: 'HARD' as QuestDifficulty,
    targetValue: 100,
    coinReward: 1000,
    xpReward: 750,
    gemReward: 50,
    isWeekly: true,
  },
  {
    name: 'Perfect Week',
    description: 'Maintain a 7-day streak',
    type: 'STREAK_BUILDER' as QuestType,
    difficulty: 'HARD' as QuestDifficulty,
    targetValue: 7,
    coinReward: 500,
    xpReward: 350,
    gemReward: 30,
    isWeekly: true,
  },
  {
    name: 'Topic Master',
    description: 'Master 5 different topics this week',
    type: 'TOPIC_MASTERY' as QuestType,
    difficulty: 'HARD' as QuestDifficulty,
    targetValue: 5,
    coinReward: 750,
    xpReward: 500,
    gemReward: 40,
    isWeekly: true,
  },
];

export async function seedQuestTemplates() {
  console.log('🎯 Seeding quest templates...');

  for (const template of questTemplates) {
    await prisma.questTemplate.upsert({
      where: { name: template.name },
      create: template,
      update: template,
    });
  }

  console.log(`✅ Seeded ${questTemplates.length} quest templates`);
}

export default seedQuestTemplates;