import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const worlds = [
  {
    name: 'Number Kingdom',
    description: 'Begin your journey in the magical Number Kingdom, where basic operations come to life!',
    order: 1,
    imageUrl: '/assets/worlds/number-kingdom.png',
    requiredLevel: 1,
    theme: 'fantasy',
  },
  {
    name: 'Fraction Forest',
    description: 'Venture into the mysterious Fraction Forest, where parts make the whole.',
    order: 2,
    imageUrl: '/assets/worlds/fraction-forest.png',
    requiredLevel: 5,
    theme: 'nature',
  },
  {
    name: 'Decimal Desert',
    description: 'Cross the vast Decimal Desert, where precision is everything.',
    order: 3,
    imageUrl: '/assets/worlds/decimal-desert.png',
    requiredLevel: 10,
    theme: 'desert',
  },
  {
    name: 'Algebra Archipelago',
    description: 'Sail through the Algebra Archipelago, solving for X on mysterious islands.',
    order: 4,
    imageUrl: '/assets/worlds/algebra-archipelago.png',
    requiredLevel: 15,
    theme: 'ocean',
  },
  {
    name: 'Geometry Galaxy',
    description: 'Blast off to the Geometry Galaxy, where shapes float among the stars!',
    order: 5,
    imageUrl: '/assets/worlds/geometry-galaxy.png',
    requiredLevel: 20,
    theme: 'space',
  },
];

export const chapters = [
  // WORLD 1: Number Kingdom (5 chapters)
  {
    worldName: 'Number Kingdom',
    name: 'The Castle Gates',
    description: 'Prove your worth to enter the Number Kingdom by mastering addition!',
    order: 1,
    requiredLevel: 1,
    minStarsToUnlock: 0,
    problemCount: 10,
    topics: ['addition', 'basic_operations'],
    difficulty: 3,
    rewardCoins: 100,
    rewardXp: 50,
    story: 'You arrive at the grand gates of the Number Kingdom. The guards challenge you to prove your mathematical skills before entry...',
  },
  {
    worldName: 'Number Kingdom',
    name: 'Market Square',
    description: 'Help the merchants with their calculations!',
    order: 2,
    requiredLevel: 2,
    minStarsToUnlock: 2,
    problemCount: 12,
    topics: ['subtraction', 'addition'],
    difficulty: 3,
    rewardCoins: 150,
    rewardXp: 75,
    story: 'The bustling market square is full of merchants who need help with their accounts. Can you assist them?',
  },
  {
    worldName: 'Number Kingdom',
    name: 'The Royal Treasury',
    description: 'Count the kingdom\'s gold using multiplication!',
    order: 3,
    requiredLevel: 3,
    minStarsToUnlock: 2,
    problemCount: 15,
    topics: ['multiplication'],
    difficulty: 4,
    rewardCoins: 200,
    rewardXp: 100,
    story: 'The royal treasurer needs your help to count the kingdom\'s wealth. Multiply your way to success!',
  },
  {
    worldName: 'Number Kingdom',
    name: 'The Great Feast',
    description: 'Divide the feast fairly among the kingdom!',
    order: 4,
    requiredLevel: 4,
    minStarsToUnlock: 2,
    problemCount: 15,
    topics: ['division'],
    difficulty: 4,
    rewardCoins: 250,
    rewardXp: 125,
    story: 'The king is hosting a grand feast! Help divide the food equally among all the guests.',
  },
  {
    worldName: 'Number Kingdom',
    name: 'The Throne Room Challenge',
    description: 'Face the king in a mixed operations challenge!',
    order: 5,
    requiredLevel: 5,
    minStarsToUnlock: 3,
    problemCount: 20,
    topics: ['all_operations', 'order_of_operations'],
    difficulty: 5,
    rewardCoins: 500,
    rewardXp: 250,
    story: 'The king himself challenges you to a mathematical duel. Prove you are worthy of his respect!',
  },

  // WORLD 2: Fraction Forest (5 chapters)
  {
    worldName: 'Fraction Forest',
    name: 'The Entrance Trail',
    description: 'Learn to navigate using fractions of the path.',
    order: 1,
    requiredLevel: 5,
    minStarsToUnlock: 0,
    problemCount: 12,
    topics: ['fractions_introduction', 'equivalent_fractions'],
    difficulty: 5,
    rewardCoins: 300,
    rewardXp: 150,
    story: 'You enter the mystical Fraction Forest, where every path is divided into parts...',
  },
  {
    worldName: 'Fraction Forest',
    name: 'The Comparing Grove',
    description: 'Compare fractions to find the best path through the grove.',
    order: 2,
    requiredLevel: 6,
    minStarsToUnlock: 2,
    problemCount: 15,
    topics: ['comparing_fractions', 'ordering_fractions'],
    difficulty: 5,
    rewardCoins: 350,
    rewardXp: 175,
    story: 'Multiple paths diverge ahead. Which fraction will lead you true?',
  },
  {
    worldName: 'Fraction Forest',
    name: 'The Addition Arbor',
    description: 'Combine fractions to build bridges across streams.',
    order: 3,
    requiredLevel: 7,
    minStarsToUnlock: 2,
    problemCount: 18,
    topics: ['adding_fractions', 'common_denominators'],
    difficulty: 6,
    rewardCoins: 400,
    rewardXp: 200,
    story: 'Streams block your path. Add fractions together to build bridges!',
  },
  {
    worldName: 'Fraction Forest',
    name: 'The Multiplication Meadow',
    description: 'Multiply fractions to unlock ancient gates.',
    order: 4,
    requiredLevel: 8,
    minStarsToUnlock: 2,
    problemCount: 18,
    topics: ['multiplying_fractions'],
    difficulty: 6,
    rewardCoins: 450,
    rewardXp: 225,
    story: 'Ancient gates covered in fraction symbols bar your way. Multiply to unlock them!',
  },
  {
    worldName: 'Fraction Forest',
    name: 'The Heart of the Forest',
    description: 'Face the Fraction Dragon in an epic battle!',
    order: 5,
    requiredLevel: 10,
    minStarsToUnlock: 3,
    problemCount: 25,
    topics: ['all_fraction_operations'],
    difficulty: 7,
    rewardCoins: 1000,
    rewardXp: 500,
    story: 'Deep in the forest\'s heart, the Fraction Dragon awaits. Only true fraction mastery will defeat it!',
  },

  // WORLD 3: Decimal Desert (5 chapters)
  {
    worldName: 'Decimal Desert',
    name: 'The Oasis of Place Value',
    description: 'Understand decimal place values to find water.',
    order: 1,
    requiredLevel: 10,
    minStarsToUnlock: 0,
    problemCount: 15,
    topics: ['decimal_place_value', 'comparing_decimals'],
    difficulty: 6,
    rewardCoins: 400,
    rewardXp: 200,
    story: 'You enter the scorching Decimal Desert. First, find the oasis by understanding decimal places...',
  },
  {
    worldName: 'Decimal Desert',
    name: 'The Precision Pyramids',
    description: 'Add and subtract decimals to explore ancient pyramids.',
    order: 2,
    requiredLevel: 11,
    minStarsToUnlock: 2,
    problemCount: 18,
    topics: ['adding_decimals', 'subtracting_decimals'],
    difficulty: 6,
    rewardCoins: 500,
    rewardXp: 250,
    story: 'Ancient pyramids rise from the sand. Precise decimal calculations will unlock their secrets!',
  },
  {
    worldName: 'Decimal Desert',
    name: 'The Multiplication Mirage',
    description: 'Multiply decimals to navigate through mirages.',
    order: 3,
    requiredLevel: 12,
    minStarsToUnlock: 2,
    problemCount: 20,
    topics: ['multiplying_decimals'],
    difficulty: 7,
    rewardCoins: 600,
    rewardXp: 300,
    story: 'Mirages deceive your eyes. Only decimal multiplication will reveal the true path!',
  },
  {
    worldName: 'Decimal Desert',
    name: 'The Division Dunes',
    description: 'Divide decimals to cross massive sand dunes.',
    order: 4,
    requiredLevel: 13,
    minStarsToUnlock: 2,
    problemCount: 20,
    topics: ['dividing_decimals'],
    difficulty: 7,
    rewardCoins: 700,
    rewardXp: 350,
    story: 'Towering dunes block your way. Divide decimals to find passages through!',
  },
  {
    worldName: 'Decimal Desert',
    name: 'The Demon\'s Lair',
    description: 'Defeat the Decimal Demon in its sandy stronghold!',
    order: 5,
    requiredLevel: 15,
    minStarsToUnlock: 3,
    problemCount: 25,
    topics: ['all_decimal_operations'],
    difficulty: 8,
    rewardCoins: 1500,
    rewardXp: 750,
    story: 'At the desert\'s heart lies the Decimal Demon\'s lair. Face it with all your decimal knowledge!',
  },

  // WORLD 4: Algebra Archipelago (5 chapters)
  {
    worldName: 'Algebra Archipelago',
    name: 'Variable Island',
    description: 'Learn the language of variables on this mysterious island.',
    order: 1,
    requiredLevel: 15,
    minStarsToUnlock: 0,
    problemCount: 15,
    topics: ['variables', 'expressions'],
    difficulty: 7,
    rewardCoins: 600,
    rewardXp: 300,
    story: 'You sail to the first island, where mysterious symbols represent unknown values...',
  },
  {
    worldName: 'Algebra Archipelago',
    name: 'Equation Atoll',
    description: 'Solve one-step equations to navigate the atoll.',
    order: 2,
    requiredLevel: 16,
    minStarsToUnlock: 2,
    problemCount: 18,
    topics: ['one_step_equations'],
    difficulty: 7,
    rewardCoins: 700,
    rewardXp: 350,
    story: 'A ring of small islands forms an atoll. Each requires solving an equation to pass!',
  },
  {
    worldName: 'Algebra Archipelago',
    name: 'The Two-Step Strait',
    description: 'Navigate the strait by solving two-step equations.',
    order: 3,
    requiredLevel: 17,
    minStarsToUnlock: 2,
    problemCount: 20,
    topics: ['two_step_equations'],
    difficulty: 8,
    rewardCoins: 800,
    rewardXp: 400,
    story: 'The strait is treacherous, requiring two steps to solve each challenge!',
  },
  {
    worldName: 'Algebra Archipelago',
    name: 'Inequality Inlet',
    description: 'Master inequalities to explore the inlet.',
    order: 4,
    requiredLevel: 18,
    minStarsToUnlock: 2,
    problemCount: 20,
    topics: ['inequalities'],
    difficulty: 8,
    rewardCoins: 900,
    rewardXp: 450,
    story: 'Not all answers are equal. Learn to work with inequalities here!',
  },
  {
    worldName: 'Algebra Archipelago',
    name: 'The Assassin\'s Fortress',
    description: 'Face the Algebra Assassin in the central fortress!',
    order: 5,
    requiredLevel: 20,
    minStarsToUnlock: 3,
    problemCount: 25,
    topics: ['multi_step_equations', 'all_algebra'],
    difficulty: 9,
    rewardCoins: 2000,
    rewardXp: 1000,
    story: 'The Algebra Assassin awaits in the fortress. Only algebraic mastery will prevail!',
  },

  // WORLD 5: Geometry Galaxy (5 chapters)
  {
    worldName: 'Geometry Galaxy',
    name: 'The Angle Asteroid Belt',
    description: 'Navigate asteroids by calculating angles.',
    order: 1,
    requiredLevel: 20,
    minStarsToUnlock: 0,
    problemCount: 18,
    topics: ['angles', 'angle_relationships'],
    difficulty: 8,
    rewardCoins: 800,
    rewardXp: 400,
    story: 'You blast off into space! First challenge: navigate an asteroid belt using angle calculations...',
  },
  {
    worldName: 'Geometry Galaxy',
    name: 'Planet Perimeter',
    description: 'Calculate perimeters to orbit planets safely.',
    order: 2,
    requiredLevel: 21,
    minStarsToUnlock: 2,
    problemCount: 20,
    topics: ['perimeter', 'polygons'],
    difficulty: 8,
    rewardCoins: 900,
    rewardXp: 450,
    story: 'Strange geometric planets float in space. Calculate their perimeters to orbit safely!',
  },
  {
    worldName: 'Geometry Galaxy',
    name: 'The Area Nebula',
    description: 'Measure areas to map the colorful nebula.',
    order: 3,
    requiredLevel: 22,
    minStarsToUnlock: 2,
    problemCount: 22,
    topics: ['area', 'composite_figures'],
    difficulty: 9,
    rewardCoins: 1000,
    rewardXp: 500,
    story: 'A beautiful nebula stretches before you. Map it by calculating areas of its shapes!',
  },
  {
    worldName: 'Geometry Galaxy',
    name: 'Volume Void',
    description: 'Calculate volumes to cross the mysterious void.',
    order: 4,
    requiredLevel: 23,
    minStarsToUnlock: 2,
    problemCount: 22,
    topics: ['volume', '3d_shapes'],
    difficulty: 9,
    rewardCoins: 1200,
    rewardXp: 600,
    story: 'A dark void blocks your path. Only 3D calculations will guide you through!',
  },
  {
    worldName: 'Geometry Galaxy',
    name: 'The Cosmic Core',
    description: 'Face the ultimate geometric challenges at the galaxy\'s heart!',
    order: 5,
    requiredLevel: 25,
    minStarsToUnlock: 3,
    problemCount: 30,
    topics: ['pythagorean_theorem', 'all_geometry'],
    difficulty: 10,
    rewardCoins: 3000,
    rewardXp: 1500,
    story: 'At the galaxy\'s core, the ultimate geometric challenges await. Prove you are the master of shapes!',
  },
];

export const npcs = [
  {
    name: 'King Calculus',
    worldName: 'Number Kingdom',
    description: 'The wise ruler of the Number Kingdom',
    imageUrl: '/assets/npcs/king-calculus.png',
    personality: 'wise, encouraging, regal',
    dialogues: {
      greeting: 'Welcome, young mathematician! I am King Calculus, ruler of this realm.',
      hint: 'Remember, every problem has a solution. Think it through step by step.',
      victory: 'Excellent work! You have proven yourself worthy!',
      defeat: 'Don\'t give up! Even the greatest mathematicians make mistakes.',
    },
  },
  {
    name: 'Lady Fraction',
    worldName: 'Fraction Forest',
    description: 'Guardian of the Fraction Forest',
    imageUrl: '/assets/npcs/lady-fraction.png',
    personality: 'mysterious, helpful, patient',
    dialogues: {
      greeting: 'The forest welcomes you, traveler. I am Lady Fraction.',
      hint: 'When working with fractions, always find common ground.',
      victory: 'You have mastered the way of parts and wholes!',
      defeat: 'Fractions can be tricky. Take your time to understand them.',
    },
  },
  {
    name: 'Sage Decimal',
    worldName: 'Decimal Desert',
    description: 'The ancient sage of the desert',
    imageUrl: '/assets/npcs/sage-decimal.png',
    personality: 'ancient, precise, calm',
    dialogues: {
      greeting: 'Precision is everything in the desert, young one.',
      hint: 'Line up your decimal points, and the path will be clear.',
      victory: 'Your precision is admirable!',
      defeat: 'Small errors can lead you astray. Be meticulous.',
    },
  },
  {
    name: 'Captain Variable',
    worldName: 'Algebra Archipelago',
    description: 'Pirate captain who sails the algebraic seas',
    imageUrl: '/assets/npcs/captain-variable.png',
    personality: 'adventurous, clever, mysterious',
    dialogues: {
      greeting: 'Ahoy, matey! Ready to solve for X?',
      hint: 'Balance the equation, like balancing a ship in stormy seas!',
      victory: 'Brilliant! You\'ve got the makings of a fine algebraic sailor!',
      defeat: 'Don\'t walk the plank yet! Try isolating the variable.',
    },
  },
  {
    name: 'Astronomer Euclid',
    worldName: 'Geometry Galaxy',
    description: 'Brilliant astronomer studying cosmic shapes',
    imageUrl: '/assets/npcs/astronomer-euclid.png',
    personality: 'intellectual, excited, cosmic',
    dialogues: {
      greeting: 'Greetings, space traveler! The shapes of the universe await!',
      hint: 'Every shape has properties. Use them to your advantage!',
      victory: 'Magnificent! The cosmos reveals its secrets to you!',
      defeat: 'Geometry is the language of the universe. Keep studying!',
    },
  },
  {
    name: 'The Mysterious Merchant',
    worldName: 'Number Kingdom',
    description: 'A traveling merchant with magical items',
    imageUrl: '/assets/npcs/merchant.png',
    personality: 'mysterious, helpful, entrepreneurial',
    dialogues: {
      greeting: 'Psst! Looking for something special? I have just what you need!',
      hint: 'Every problem is an opportunity for profit... er, learning!',
      victory: 'A wise investment of your time! Come back anytime!',
      defeat: 'No refunds on effort, but you can always try again!',
    },
  },
];

export async function seedStory() {
  console.log('📖 Seeding story content...');

  // Seed worlds
  for (const world of worlds) {
    await prisma.world.upsert({
      where: { name: world.name },
      create: world,
      update: world,
    });
  }

  // Seed chapters
  for (const chapter of chapters) {
    const world = await prisma.world.findUnique({
      where: { name: chapter.worldName },
    });

    if (world) {
      await prisma.chapter.upsert({
        where: {
          worldId_order: {
            worldId: world.id,
            order: chapter.order,
          },
        },
        create: {
          ...chapter,
          worldId: world.id,
          worldName: undefined,
        },
        update: {
          ...chapter,
          worldName: undefined,
        },
      });
    }
  }

  // Seed NPCs
  for (const npc of npcs) {
    const world = await prisma.world.findUnique({
      where: { name: npc.worldName },
    });

    if (world) {
      await prisma.nPC.upsert({
        where: { name: npc.name },
        create: {
          ...npc,
          worldId: world.id,
          worldName: undefined,
        },
        update: {
          ...npc,
          worldName: undefined,
        },
      });
    }
  }

  console.log(`✅ Seeded ${worlds.length} worlds, ${chapters.length} chapters, and ${npcs.length} NPCs`);
}

export default seedStory;